name: Build & Run Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Install JFrog CLI
        run: |
          curl -fL https://install-cli.jfrog.io | sh

      - name: Configure JFrog CLI server
        run: |
          jf config add my-jfrog-server \
            --url="${{ secrets.https://trialea6yjn.jfrog.io }}" \
            --user="${{ secrets.sandeepmgvr2210@zohomail.in }}" \
            --password="${{ secrets.2210wccS@1994 }}" \
            --interactive=false

      - name: Upload artifact to JFrog Artifactory
        run: |
          jf rt upload \
            "target/*.jar" \
            "${{ secrets.JFROG_REPO }}/springboot-app/" \
            --server-id=my-jfrog-server

      - name: Run Spring Boot Application
        run: mvn spring-boot:run
